name: Build Shopping Hub

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "No build script found in package.json" && exit 1
          fi

      - name: Zip build directory
        if: success()
        run: |
          if [ -d dist ] || [ -d build ]; then
            DIR=$( [ -d dist ] && echo dist || echo build )
            zip -r build.zip "$DIR"
          else
            echo "No build output directory (dist or build) found" && exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip
